feat: create custom WP filter for overriding default ACF location of …
whitespace-se/wordpress-plugin-a11ystack pull request #1
Opened 2022-03-03 09:25 UTC by hinderson

I've added a new WP filter for overriding the location of the new `openGraph` fields.

2022-03-03 09:31 UTC, jeanfredrik commented
Can you simplify the filter so that it just passes a one-dimensional array of post types instead of the whole `location` array? Also the name of the plugin is `whitespace-a11ystack` and it will probably contain more stuff in the future so the filter name should be changed and be more specific, e.g. `whitespace-a11ystack/open_graph/enabled_post_types`.

2022-03-03 09:32 UTC, jeanfredrik requested changes
See my comment in the convo

2022-03-03 09:39 UTC, hinderson commented
So like this?

```
add_filter("whitespace-a11ystack/open_graph/enabled_post_types", function() {
  return ['post', 'page', 'broadcast'];
});
```

2022-03-04 09:44 UTC, jeanfredrik approved these changes
Yes, perfect 👌

2022-03-04 09:44 UTC, merged